FROM debian:10

RUN apt-get update
RUN apt-get install -y xz-utils libcap2-bin jq

ARG BUILD=release
RUN set -ex; \
  if [ "$BUILD" = "debug" ]; then \
		apt-get install -y strace procps elfutils gdb binutils vim patchelf; \
	fi

COPY fastfreeze.tar.xz /tmp

RUN set -ex; \
  tar xf /tmp/fastfreeze.tar.xz -C /opt; \
  ln -s /opt/fastfreeze/fastfreeze /usr/local/bin/

WORKDIR /opt/fastfreeze
